import { GoogleGenAI, Type } from "@google/genai";

export const config = {
  maxDuration: 60,
};

function getGenAI(): GoogleGenAI {
  const key = process.env.GEMINI_API_KEY;
  if (!key) {
    throw new Error(
      "GEMINI_API_KEY belum dikonfigurasi. Silakan tambahkan 'GEMINI_API_KEY' pada menu Settings > Environment Variables di dashboard Vercel Anda, lalu lakukan redeploy."
    );
  }
  return new GoogleGenAI({
    apiKey: key,
    httpOptions: {
      headers: {
        "User-Agent": "aistudio-build",
      },
    },
  });
}

async function generateContentWithRetryAndFallback(
  ai: GoogleGenAI,
  models: string[],
  contents: any,
  genConfig: any
): Promise<any> {
  let lastError: any = null;

  for (const model of models) {
    let attempt = 0;
    const maxRetries = 1;

    while (attempt <= maxRetries) {
      try {
        console.log(`[Vercel Serverless] Trying model "${model}" (Attempt ${attempt + 1})...`);
        const response = await ai.models.generateContent({
          model,
          contents,
          config: genConfig,
        });

        if (response && response.text) {
          console.log(`[Vercel Serverless] Success with model "${model}"!`);
          return response;
        }

        throw new Error("Empty response generated by AI model");
      } catch (err: any) {
        attempt++;
        lastError = err;
        const errStr = err?.message || String(err);
        console.warn(`[Vercel Serverless] Attempt ${attempt} on model "${model}" failed:`, errStr);

        // If the model is overloaded or unavailable (503 / high demand), failover immediately without wasting time
        const isOverloadedOrUnavailable = 
          errStr.includes("503") || 
          errStr.toLowerCase().includes("unavailable") || 
          errStr.toLowerCase().includes("overloaded") ||
          errStr.toLowerCase().includes("high demand");

        if (isOverloadedOrUnavailable) {
          console.log(`[Vercel Serverless] Model "${model}" is overloaded (503). Immediately failing over to next available model...`);
          break; // Try next model immediately
        }

        const isRateLimited = errStr.includes("429") || errStr.toLowerCase().includes("resource exhausted");
        if (isRateLimited && attempt <= maxRetries) {
          await new Promise((resolve) => setTimeout(resolve, 800));
        } else {
          break;
        }
      }
    }
  }

  throw lastError || new Error("Semua model AI sedang mengalami beban tinggi. Silakan coba beberapa saat lagi.");
}

export default async function handler(req: any, res: any) {
  // Set CORS headers
  res.setHeader("Access-Control-Allow-Credentials", "true");
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET,OPTIONS,PATCH,DELETE,POST,PUT");
  res.setHeader(
    "Access-Control-Allow-Headers",
    "X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version"
  );

  if (req.method === "OPTIONS") {
    res.statusCode = 200;
    return res.end();
  }

  if (req.method !== "POST") {
    res.statusCode = 405;
    res.setHeader("Content-Type", "application/json");
    return res.end(JSON.stringify({ error: "Method not allowed. Only POST is supported." }));
  }

  try {
    // Parse request body safely
    let body = req.body;
    if (typeof body === "string") {
      try {
        body = JSON.parse(body);
      } catch {
        body = {};
      }
    } else if (!body) {
      const buffers: Buffer[] = [];
      for await (const chunk of req) {
        buffers.push(typeof chunk === "string" ? Buffer.from(chunk) : chunk);
      }
      const raw = Buffer.concat(buffers).toString("utf-8");
      if (raw) {
        try {
          body = JSON.parse(raw);
        } catch {
          body = {};
        }
      } else {
        body = {};
      }
    }

    const {
      courseName,
      courseCode,
      prodi,
      fakultas,
      sksTeori,
      sksPraktik,
      semester,
      theme,
      academicCpls = [],
      dosenPengembang = "",
      nidnDosenPengembang = "",
      koordinatorRMK = "",
      nidnKoordinatorRMK = "",
      koordinatorProdi = "",
      nidnKoordinatorProdi = "",
      customNotes = "",
    } = body;

    if (!courseName) {
      res.statusCode = 400;
      res.setHeader("Content-Type", "application/json");
      return res.end(JSON.stringify({ error: "Nama mata kuliah wajib diisi" }));
    }

    const ai = getGenAI();

    const cplGuidance = academicCpls.length > 0
      ? academicCpls.map((c: any) => `- ID: "${c.id}", Kode: "${c.kode}", Kategori: "${c.kategori}", Deskripsi: "${c.deskripsi}"`).join("\n")
      : "CPL Program Studi standar BAN-PT.";

    const systemInstruction = `Anda adalah Asesor BAN-PT dan ahli kurikulum akademik perguruan tinggi di Indonesia, yang menguasai konsep Outcome-Based Education (OBE). 
Tugas Anda adalah merumuskan draf Rencana Pembelajaran Semester (RPS) yang lengkap, rinci, terukur, dan sangat akademis untuk mata kuliah "${courseName}" di "${prodi}", Institut KH. Ahmad Sanusi Sukabumi.

Mata kuliah ini harus mengacu pada kerangka CPL (Capaian Pembelajaran Lulusan), CPMK (Capaian Pembelajaran Mata Kuliah) yang disusun berbasis taksonomi Bloom, Sub-CPMK, serta rincian lengkap 16 Pertemuan.

Instruksi Teknis Mutlak:
1. CAPAIAN PEMBELAJARAN LULUSAN (CPL):
   Anda WAJIB dan hanya boleh menggunakan referensi CPL resmi dari Program Studi yang dipilih berikut ini. JANGAN membuat, memodifikasi, atau memalsukan kode/ID/deskripsi CPL baru yang tidak ada di daftar ini. Masukkan CPL yang relevan untuk mata kuliah ini ke dalam array "cpl" dengan data JSON (id, kode, deskripsi, kategori) yang PERSIS SAMA dengan daftar di bawah ini:
   ${cplGuidance}

2. CPMK & SUB-CPMK:
   - CPMK: Rumuskan 3 hingga 5 CPMK yang berorientasi hasil yang bisa didemonstrasikan. Setiap CPMK harus terhubung dengan minimal 1 CPL yang telah dipilih di atas dengan mencantumkan "id" CPL yang bersangkutan dalam array "cplIds" (misalnya: "CPL-HKI-3", "CPL-PAI-2", dll).
   - Sub-CPMK: Pecah menjadi 10-14 Sub-CPMK spesifik yang mengarah pada CPMK pencapaian tertentu, lengkap dengan verbs taksonomi Bloom yang tepat (C3-C6: Menganalisa, Mengevaluasi, Merancang, Mengaplikasikan). Setiap Sub-CPMK harus terhubung dengan cpmkId yang sesuai.

3. 16 PERTEMUAN (STRUTUR WAJIB):
   Tabel 16 Pertemuan harus diisi dengan sangat detail. Tidak boleh ada baris kosong, singkatan malas, atau tiruan "Sda" (sama dengan atas).
   - Pertemuan 1-7: Kegiatan pembelajaran bertahap yang mengacu pada Sub-CPMK-1 s.d Sub-CPMK-7.
   - Pertemuan 8: HARUS diisi sebagai "Ujian Tengah Semester (UTS)". Rumuskan indikator kelulusannya, kriteria pengujian (tertulis, kasus), bobot (%) adalah 15-20%.
   - Pertemuan 9-15: Kegiatan pembelajaran lanjutan mengacu pada Sub-CPMK-8 s.d Sub-CPMK-14.
   - Pertemuan 16: HARUS diisi sebagai "Ujian Akhir Semester (UAS)". Penilaian menyeluruh, bobot (%) adalah 20-30%.
   - Total bobot dari Pertemuan 1 s/d 16 harus persis berjumlah 100%.

4. BENTUK PEMBELAJARAN & METODE (LURING & DARING):
   Metode harus relevan dengan OBE (seperti: "Kuliah teori, diskusi kelompok, case method, project-based learning"). Jelaskan estimasi waktunya (misal: "TM: 2x50 mnt", "Tugas mandiri: 60 mnt").
   Karena kampus terintegrasi dengan Portal SSO Pintar, wajib sebutkan integrasi LMS (seperti: "Membaca draf di LMS kampus via SSO", "Latihan kuis mandiri di portal").

5. RENCANA TUGAS MAHASISWA & KONTRAK PERKULIAHAN:
   Susun 1 Tugas utama RTM (Rencana Tugas Mahasiswa) berskala kelompok/mandiri dengan langkah rincian pengerjaan, format luaran, rubrik indikator penilaian, bobot kriteria.
   Lengkapi Kontrak perkuliahan: hak dan kewajiban dosen & mahasiswa, serta tata tertib perkuliahan di Institut KH. Ahmad Sanusi Sukabumi.

Penting: Gunakan bahasa Indonesia yang baku, profesional, bernuansa akademis Islam terhormat terpadu dengan sains modern! Gunakan "Institut KH. Ahmad Sanusi Sukabumi" di seluruh nama instansi.`;

    const userPrompt = `Buatkan draf lengkap RPS berbasis OBE untuk:
Mata Kuliah: ${courseName}
Kode MK: ${courseCode || "AUTO-" + Math.floor(1000 + Math.random() * 9000)}
Program Studi: ${prodi}
Fakultas: ${fakultas || "Fakultas Syariah"}
SKS: Teori = ${sksTeori || 2}, Praktik = ${sksPraktik || 0}
Semester: ${semester || 1}
Rumpun MK / Bidang Kajian: ${theme}

Ketentuan Khusus OBE & CPL:
Pilih dan generates draf Capaian Pembelajaran Lulusan (CPL) eksklusif dari list CPL resmi Program Studi yang dikirimkan di atas. JANGAN mengarang CPL atau ID CPL baru di luar list tersebut. Pastikan CPMK memetakan 'cplIds' yang merujuk pada id CPL asal yang benar dari list tersebut.

Data Tim Dosen & Pengesahan (Harus dimasukkan ke 'meta'):
Dosen Pengembang RPS: ${dosenPengembang || "Dosen Pengembang Terverifikasi"}
NIDN Dosen Pengembang: ${nidnDosenPengembang || "-"}
Koordinator RMK: ${koordinatorRMK || "Koordinator Rumpun Mata Kuliah"}
NIDN Koordinator RMK: ${nidnKoordinatorRMK || "-"}
Ketua / Koordinator Program Studi: ${koordinatorProdi || "Ketua Program Studi"}
NIDN Koordinator Prodi: ${nidnKoordinatorProdi || "-"}

Catatan & Ekspektasi Dosen Pengajar:
${customNotes || "Sesuaikan secara mutakhir dengan standar BAN-PT dan OBE Nasional."}

Buatlah struktur JSON valid yang lengkap sesuai responseSchema tanpa teks pembuka atau penutup markdown.`;

    const modelsToTry = [
      "gemini-3.6-flash",
      "gemini-3.1-flash-lite",
      "gemini-flash-latest",
      "gemini-3.8-flash",
    ];

    const response = await generateContentWithRetryAndFallback(
      ai,
      modelsToTry,
      userPrompt,
      {
        systemInstruction,
        responseMimeType: "application/json",
        responseSchema: {
          type: "OBJECT",
          required: ["meta", "cpl", "cpmk", "subCpmk", "pertemuan", "rencanaTugas", "kontrakPerkuliahan"],
          properties: {
            meta: {
              type: "OBJECT",
              required: [
                "namaMataKuliah",
                "kodeMK",
                "rumpunMK",
                "sksteori",
                "skspraktik",
                "semester",
                "programStudi",
                "tanggalPenyusunan",
                "dosenPengembang",
                "nidnDosenPengembang",
                "koordinatorRMK",
                "nidnKoordinatorRMK",
                "koordinatorProdi",
                "nidnKoordinatorProdi",
                "deskripsiSingkat",
                "bahanKajian",
                "pustakaUtama",
                "pustakaPendukung",
                "dosenPengampu",
                "mataKuliahSyarat",
                "institusi",
                "fakultas"
              ],
              properties: {
                namaMataKuliah: { type: "STRING" },
                kodeMK: { type: "STRING" },
                rumpunMK: { type: "STRING" },
                sksteori: { type: "INTEGER" },
                skspraktik: { type: "INTEGER" },
                semester: { type: "INTEGER" },
                programStudi: { type: "STRING" },
                tanggalPenyusunan: { type: "STRING" },
                dosenPengembang: { type: "STRING" },
                nidnDosenPengembang: { type: "STRING" },
                koordinatorRMK: { type: "STRING" },
                nidnKoordinatorRMK: { type: "STRING" },
                koordinatorProdi: { type: "STRING" },
                nidnKoordinatorProdi: { type: "STRING" },
                deskripsiSingkat: { type: "STRING" },
                bahanKajian: { type: "ARRAY", items: { type: "STRING" } },
                pustakaUtama: { type: "ARRAY", items: { type: "STRING" } },
                pustakaPendukung: { type: "ARRAY", items: { type: "STRING" } },
                dosenPengampu: { type: "ARRAY", items: { type: "STRING" } },
                mataKuliahSyarat: { type: "STRING" },
                institusi: { type: "STRING" },
                fakultas: { type: "STRING" }
              }
            },
            cpl: {
              type: "ARRAY",
              items: {
                type: "OBJECT",
                required: ["id", "kode", "deskripsi", "kategori"],
                properties: {
                  id: { type: "STRING" },
                  kode: { type: "STRING" },
                  deskripsi: { type: "STRING" },
                  kategori: { type: "STRING" }
                }
              }
            },
            cpmk: {
              type: "ARRAY",
              items: {
                type: "OBJECT",
                required: ["id", "deskripsi", "cplIds"],
                properties: {
                  id: { type: "STRING" },
                  deskripsi: { type: "STRING" },
                  cplIds: { type: "ARRAY", items: { type: "STRING" } }
                }
              }
            },
            subCpmk: {
              type: "ARRAY",
              items: {
                type: "OBJECT",
                required: ["id", "deskripsi", "cpmkId"],
                properties: {
                  id: { type: "STRING" },
                  deskripsi: { type: "STRING" },
                  cpmkId: { type: "STRING" }
                }
              }
            },
            pertemuan: {
              type: "ARRAY",
              description: "Must contain exactly 16 objects representing each week in chronological order.",
              items: {
                type: "OBJECT",
                required: [
                  "mingguKe",
                  "subCpmk",
                  "indikator",
                  "kriteriaDanTeknik",
                  "metodeLuring",
                  "metodeDaring",
                  "materiPembelajaran",
                  "bobotPenilaian"
                ],
                properties: {
                  mingguKe: { type: "INTEGER" },
                  subCpmk: { type: "STRING" },
                  indikator: { type: "STRING" },
                  kriteriaDanTeknik: { type: "STRING" },
                  metodeLuring: { type: "STRING" },
                  metodeDaring: { type: "STRING" },
                  materiPembelajaran: { type: "STRING" },
                  bobotPenilaian: { type: "INTEGER" }
                }
              }
            },
            rencanaTugas: {
              type: "OBJECT",
              required: [
                "judul",
                "bentukTugas",
                "deskripsiTugas",
                "metodePengerjaan",
                "bentukLuaran",
                "indikatorPenilaian",
                "bobotNilai",
                "jadwal"
              ],
              properties: {
                judul: { type: "STRING" },
                bentukTugas: { type: "STRING" },
                deskripsiTugas: { type: "STRING" },
                metodePengerjaan: { type: "ARRAY", items: { type: "STRING" } },
                bentukLuaran: { type: "STRING" },
                indikatorPenilaian: { type: "ARRAY", items: { type: "STRING" } },
                bobotNilai: { type: "INTEGER" },
                jadwal: { type: "STRING" }
              }
            },
            rencanaTugasMandiri: {
              type: "OBJECT",
              required: [
                "judul",
                "bentukTugas",
                "deskripsiTugas",
                "metodePengerjaan",
                "bentukLuaran",
                "indikatorPenilaian",
                "bobotNilai",
                "jadwal"
              ],
              properties: {
                judul: { type: "STRING" },
                bentukTugas: { type: "STRING" },
                deskripsiTugas: { type: "STRING" },
                metodePengerjaan: { type: "ARRAY", items: { type: "STRING" } },
                bentukLuaran: { type: "STRING" },
                indikatorPenilaian: { type: "ARRAY", items: { type: "STRING" } },
                bobotNilai: { type: "INTEGER" },
                jadwal: { type: "STRING" }
              }
            },
            kontrakPerkuliahan: {
              type: "OBJECT",
              required: ["hakKewajiban", "tataTertib", "kriteriaKelulusan"],
              properties: {
                hakKewajiban: { type: "ARRAY", items: { type: "STRING" } },
                tataTertib: { type: "ARRAY", items: { type: "STRING" } },
                kriteriaKelulusan: {
                  type: "OBJECT",
                  required: ["hadir", "tugasTerstruktur", "tugasMandiri", "tugas", "uts", "uas"],
                  properties: {
                    hadir: { type: "INTEGER" },
                    tugasTerstruktur: { type: "INTEGER" },
                    tugasMandiri: { type: "INTEGER" },
                    tugas: { type: "INTEGER" },
                    uts: { type: "INTEGER" },
                    uas: { type: "INTEGER" }
                  }
                }
              }
            }
          }
        }
      }
    );

    const textOutput = response.text;
    if (!textOutput) {
      throw new Error("No response content generated by the AI model");
    }

    const cleanedJson = JSON.parse(textOutput.trim());
    res.statusCode = 200;
    res.setHeader("Content-Type", "application/json");
    return res.end(JSON.stringify(cleanedJson));

  } catch (error: any) {
    console.error("RPS Generation failed in Vercel handler:", error);

    const errorMessage = error instanceof Error
      ? error.message
      : (error?.message || (typeof error === "object" ? JSON.stringify(error) : String(error)));

    res.statusCode = 500;
    res.setHeader("Content-Type", "application/json");
    return res.end(
      JSON.stringify({
        error: "Gagal memproses pembuatan RPS dengan AI",
        details: errorMessage,
      })
    );
  }
}
